version: '3'

services:
  hospital:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: noetic
    environment: 
      - DISPLAY # for Gazebo UI in general
      - NVIDIA_VISIBLE_DEVICES=all # for Gazebo UI using docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for Gazebo UI using docker-nvidia2
      - "PYTHONUNBUFFERED=1" # important to show error messages if a ros service crashes!
      - "ROS_DISTRO=noetic"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro  # for Gazebo UI in general
    privileged: true # for Gazebo UI in general
    expose:
      - 11345 # Gazebo
      - 11311 # ROScore
    command: ["roslaunch", "gazebo_actor_in_hospital", "view_hospital.launch", "--screen"]